import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Module 1: ROS 2 Foundations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-ros2',
        }
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation First',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-simulation',
        }
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Isaac Platform',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-isaac',
        }
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Humanoids',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vla',
        }
      ],
    },
  ],
};

export default sidebars;
